/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.ui;

import atlantafx.base.theme.PrimerLight;
import demo.ui.components.ElementTable;
import demo.ui.dto.CustomerDto;
import demo.ui.dto.JwtTokenDto;
import demo.ui.dto.PageDto;
import demo.ui.utils.Response;
import demo.ui.utils.Session;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.util.Pair;

import java.io.IOException;
import java.util.List;
import java.util.Map;

public class App extends Application {
    @Override
    public void start(Stage stage) throws IOException, Exception {
        Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());

        Session session = new Session(); // Initializing HTTP Session

        Response<JwtTokenDto> loginRes =
                session.post("/auth/login",
                        Map.of("email", "admin@localhost", "password", "admin")); // Do Login request

        System.out.println(loginRes.getStatus());
        System.out.println(loginRes.getMessage());
        System.out.println(loginRes.getData(JwtTokenDto.class).token);

        session.setToken(loginRes.getData(JwtTokenDto.class).token); // Set JWT token to session

        AnchorPane root = new AnchorPane();

        ElementTable<CustomerDto> table = new ElementTable<>(CustomerDto.class);

        table.setPrefSize(600, 400);
        table.setDialogSize(300, 200); // Set dialog size
        table.setMaxPageIndicatorCount(3); // Set max page indicator count

        table.setColumns(List.of(
                new Pair<>("Id", "id"),
                new Pair<>("Name", "name"),
                new Pair<>("E-mail", "email")
        )); // Set columns

        table.setPageCallback((pageIndex) -> {
            Response<PageDto<CustomerDto>> res =
                    session.get("/customer/getAllCustomers",
                            Map.of("page", String.valueOf(pageIndex), "size", "1"));
            return res.getData(PageDto.class);
        }); // Set page callback, return PageDto<CustomerDto> object

        table.setDoubleClickRenderer((customer) -> {
            AnchorPane dialogRoot = new AnchorPane();

            Label label = new Label("Customer ID: " + customer.id + "\n" +
                    "Customer Name: " + customer.name + "\n" +
                    "Customer E-mail: " + customer.email);
            label.setLayoutX(0);
            label.setLayoutY(0);
            dialogRoot.getChildren().add(label);

            return dialogRoot;
        }); // Set double-click renderer, return AnchorPane object as dialog root

        root.getChildren().add(table);

        Button button = new Button("Show table in another style!");
        button.setLayoutX(0);
        button.setLayoutY(400);
        button.setOnAction((event) -> {
            table.setPageCallback((pageIndex) -> {
                Response<PageDto<CustomerDto>> res =
                        session.get("/customer/getAllCustomers",
                                Map.of("page", String.valueOf(pageIndex), "size", "5"));
                return res.getData(PageDto.class);
            }); // Set page callback, return PageDto<CustomerDto> object
        });

        root.getChildren().add(button);

        Scene scene = new Scene(root, 640, 480);
        stage.setScene(scene);
        stage.show();

    }


    public static void main(String[] args) throws Exception {
        launch();
    }
}